---
- hosts: localhost
  tasks:
    - name: create deployment
      shell: kubectl create secret --namespace=NAMESPACE_USERCHOOSE  generic mysql-secret --from-literal=mysqlrootpassword=MYSQL_USER_PASSWORD --from-literal=mysqluserpassword=MYSQL_ROOT_PASSWORD