apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      component: node-app-deployment
  template:
    metadata:
      labels:
        component: node-app-deployment
    spec:
      containers:
      - name: node-app-deployment
        image: 192.168.99.122:32521/vodafonetask1node:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        imagePullSecrets:
          - name: nexus-login
        ports:
        - containerPort: 3000
        env:
          - name: HOST
            value: mysql-nodeport
          - name: DATABASE
            value: task1database
          - name: USERNAME
            valueFrom:
                secretKeyRef:
                  name: mysql-user
                  key: MYSQL_USER
          - name: PASSWORD
            valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysqluserpassword